import 'package:flutter/material.dart';

class EmojiSelectionScreen extends StatefulWidget {
  final String? currentEmoji;
  final Function(String) onEmojiSelected;

  const EmojiSelectionScreen({
    Key? key,
    this.currentEmoji,
    required this.onEmojiSelected,
  }) : super(key: key);

  @override
  State<EmojiSelectionScreen> createState() => _EmojiSelectionScreenState();
}

class _EmojiSelectionScreenState extends State<EmojiSelectionScreen> {
  final TextEditingController _searchController = TextEditingController();
  final Map<String, List<String>> _emojiCategories = {};
  final Map<String, String> _emojiKeywords = {};
  List<String> _filteredEmojis = [];
  List<String> _categoryTabs = [];
  String _selectedCategory = 'All';
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    _searchController.addListener(_filterEmojis);
    _loadEmojis();
  }

  @override
  void dispose() {
    _searchController.dispose();
    super.dispose();
  }

  void _loadEmojis() {
    // Load emojis in background to avoid UI freeze
    Future.microtask(() {
      _initializeEmojiData();
      if (mounted) {
        setState(() {
          _isLoading = false;
          _filteredEmojis = _getAllEmojis();
        });
      }
    });
  }

  void _initializeEmojiData() {
    // Define emojis by categories
    _emojiCategories['Smileys & People'] = [
      '😀',
      '😃',
      '😄',
      '😁',
      '😆',
      '😅',
      '😂',
      '🤣',
      '😊',
      '😇',
      '🙂',
      '🙃',
      '😉',
      '😌',
      '😍',
      '🥰',
      '😘',
      '😗',
      '😙',
      '😚',
      '😋',
      '😛',
      '😝',
      '😜',
      '🤪',
      '🤨',
      '🧐',
      '🤓',
      '😎',
      '🤩',
      '🥳',
      '😏',
      '😒',
      '😞',
      '😔',
      '😟',
      '😕',
      '🙁',
      '☹️',
      '😣',
      '😖',
      '😫',
      '😩',
      '🥺',
      '😢',
      '😭',
      '😤',
      '😠',
      '😡',
      '🤬',
      '🤯',
      '😳',
      '🥵',
      '🥶',
      '😱',
      '😨',
      '😰',
      '😥',
      '😓',
      '🤗',
      '🤔',
      '🤭',
      '🤫',
      '🤥',
      '😶',
      '😐',
      '😑',
      '😬',
      '🙄',
      '😯',
      '😦',
      '😧',
      '😮',
      '😲',
      '🥱',
      '😴',
      '🤤',
      '😪',
      '😵',
      '🤐',
      '🥴',
      '🤢',
      '🤮',
      '🤧',
      '😷',
      '🤒',
      '🤕',
      '🤑',
      '🤠',
      '😈',
      '👿',
      '👹',
      '👺',
      '🤡',
      '💩',
      '👻',
      '💀',
      '☠️',
      '👽',
      '👾',
      '🤖',
      '🎃',
      '😺',
      '😸',
      '😹',
      '😻',
      '😼',
      '😽',
      '🙀',
      '😿',
      '😾'
    ];

    _emojiCategories['Hands & Body'] = [
      '👋',
      '🤚',
      '🖐️',
      '✋',
      '🖖',
      '👌',
      '🤌',
      '🤏',
      '✌️',
      '🤞',
      '🤟',
      '🤘',
      '🤙',
      '👈',
      '👉',
      '👆',
      '🖕',
      '👇',
      '☝️',
      '👍',
      '👎',
      '✊',
      '👊',
      '🤛',
      '🤜',
      '👏',
      '🙌',
      '👐',
      '🤲',
      '🤝',
      '🙏',
      '✍️',
      '💅',
      '🤳',
      '💪',
      '🦾',
      '🦿',
      '🦵',
      '🦶',
      '👂',
      '🦻',
      '👃',
      '🧠',
      '🦷',
      '🦴',
      '👀',
      '👁️',
      '👅',
      '👄'
    ];

    _emojiCategories['People & Fantasy'] = [
      '👶',
      '🧒',
      '👦',
      '👧',
      '🧑',
      '👱',
      '👨',
      '🧔',
      '👨‍🦰',
      '👨‍🦱',
      '👨‍🦳',
      '👨‍🦲',
      '👩',
      '👩‍🦰',
      '👩‍🦱',
      '👩‍🦳',
      '👩‍🦲',
      '🧓',
      '👴',
      '👵',
      '🙍',
      '🙎',
      '🙅',
      '🙆',
      '💁',
      '🙋',
      '🧏',
      '🙇',
      '🤦',
      '🤷',
      '👮',
      '🕵️',
      '💂',
      '👷',
      '🤴',
      '👸',
      '👳',
      '👲',
      '🧕',
      '🤵',
      '👰',
      '🤰',
      '🤱',
      '👼',
      '🎅',
      '🤶',
      '🦸',
      '🦹',
      '🧙',
      '🧚',
      '🧛',
      '🧜',
      '🧝',
      '🧞',
      '🧟',
      '💆',
      '💇',
      '🚶',
      '🧍',
      '🧎',
      '🏃',
      '💃',
      '🕺',
      '🕴️',
      '👯',
      '🧖',
      '🧗',
      '🤺',
      '🏇',
      '⛷️',
      '🏂',
      '🏌️',
      '🏄',
      '🚣',
      '🏊',
      '⛹️',
      '🏋️',
      '🚴',
      '🚵',
      '🤸',
      '🤼',
      '🤽',
      '🤾',
      '🤹',
      '🧘',
      '🛀',
      '🛌',
      '👭',
      '👫',
      '👬',
      '💏',
      '💑',
      '👪'
    ];

    _emojiCategories['Nature & Animals'] = [
      '🌍',
      '🌎',
      '🌏',
      '🌐',
      '🗺️',
      '🧭',
      '🏔️',
      '⛰️',
      '🌋',
      '🗻',
      '🏕️',
      '🏖️',
      '🏜️',
      '🏝️',
      '🏞️',
      '🏟️',
      '🏛️',
      '🏗️',
      '🧱',
      '🏘️',
      '🏚️',
      '🏠',
      '🏡',
      '🏢',
      '🏣',
      '🏤',
      '🏥',
      '🏦',
      '🏨',
      '🏩',
      '🏪',
      '🏫',
      '🏬',
      '🏭',
      '🏯',
      '🏰',
      '💒',
      '🗼',
      '🗽',
      '⛪',
      '🕌',
      '🛕',
      '🕍',
      '⛩️',
      '🕋',
      '⛲',
      '⛺',
      '🌁',
      '🌃',
      '🏙️',
      '🌄',
      '🌅',
      '🌆',
      '🌇',
      '🌉',
      '♨️',
      '🎠',
      '🎡',
      '🎢',
      '💈',
      '🎪'
    ];

    _emojiCategories['Food & Drink'] = [
      '🍎',
      '🍏',
      '🍐',
      '🍊',
      '🍋',
      '🍌',
      '🍉',
      '🍇',
      '🍓',
      '🫐',
      '🍈',
      '🍒',
      '🍑',
      '🥭',
      '🍍',
      '🥥',
      '🥝',
      '🍅',
      '🍆',
      '🥑',
      '🥦',
      '🥬',
      '🥒',
      '🌶️',
      '🫑',
      '🌽',
      '🥕',
      '🫒',
      '🧄',
      '🧅',
      '🥔',
      '🍠',
      '🥐',
      '🥯',
      '🍞',
      '🥖',
      '🥨',
      '🧀',
      '🥚',
      '🍳',
      '🧈',
      '🥞',
      '🧇',
      '🥓',
      '🥩',
      '🍗',
      '🍖',
      '🦴',
      '🌭',
      '🍔',
      '🍟',
      '🍕',
      '🫓',
      '🥪',
      '🥙',
      '🧆',
      '🌮',
      '🌯',
      '🫔',
      '🥗',
      '🥘',
      '🫕',
      '🥫',
      '🍝',
      '🍜',
      '🍲',
      '🍛',
      '🍣',
      '🍱',
      '🥟',
      '🦪',
      '🍤',
      '🍙',
      '🍚',
      '🍘',
      '🍥',
      '🥠',
      '🥮',
      '🍢',
      '🍡',
      '🍧',
      '🍨',
      '🍦',
      '🥧',
      '🧁',
      '🍰',
      '🎂',
      '🍮',
      '🍭',
      '🍬',
      '🍫',
      '🍿',
      '🍩',
      '🍪',
      '🌰',
      '🥜',
      '🍯',
      '🥛',
      '🍼',
      '🫖',
      '☕',
      '🍵',
      '🧃',
      '🥤',
      '🧋',
      '🍶',
      '🍺',
      '🍻',
      '🥂',
      '🍷',
      '🥃',
      '🍸',
      '🍹',
      '🧉',
      '🍾',
      '🧊',
      '🥄',
      '🍴',
      '🍽️',
      '🥣',
      '🥡',
      '🥢',
      '🧂'
    ];

    _emojiCategories['Activities & Sports'] = [
      '⚽',
      '⚾',
      '🥎',
      '🏀',
      '🏐',
      '🏈',
      '🏉',
      '🎾',
      '🥏',
      '🎳',
      '🏏',
      '🏑',
      '🏒',
      '🥍',
      '🏓',
      '🏸',
      '🥊',
      '🥋',
      '🥅',
      '⛳',
      '⛸️',
      '🎣',
      '🤿',
      '🎽',
      '🎿',
      '🛷',
      '🥌',
      '🎯',
      '🪀',
      '🪁',
      '🔫',
      '🎱',
      '🔮',
      '🎮',
      '🕹️',
      '🎰',
      '🎲',
      '🧩',
      '♠️',
      '♥️',
      '♦️',
      '♣️',
      '🃏',
      '🀄',
      '🎴',
      '🎭',
      '🖼️',
      '🎨',
      '🧵',
      '🧶'
    ];

    _emojiCategories['Objects & Symbols'] = [
      '👓',
      '🕶️',
      '🥽',
      '🥼',
      '🦺',
      '👔',
      '👕',
      '👖',
      '🧣',
      '🧤',
      '🧥',
      '🧦',
      '👗',
      '👘',
      '🥻',
      '🩱',
      '🩲',
      '🩳',
      '👙',
      '👚',
      '👛',
      '👜',
      '👝',
      '🎒',
      '👞',
      '👟',
      '🥾',
      '🥿',
      '👠',
      '👡',
      '🩰',
      '👢',
      '👑',
      '👒',
      '🎩',
      '🎓',
      '🧢',
      '⛑️',
      '💄',
      '💍',
      '💼',
      '🌂',
      '☂️',
      '🧳',
      '📱',
      '📲',
      '💻',
      '⌨️',
      '🖥️',
      '🖨️',
      '🖱️',
      '🖲️',
      '💽',
      '💾',
      '💿',
      '📀',
      '📼',
      '📷',
      '📸',
      '📹',
      '🎥',
      '📽️',
      '🎞️',
      '📞',
      '☎️',
      '📟',
      '📠',
      '📺',
      '📻',
      '🎙️',
      '🎚️',
      '🎛️',
      '🧭',
      '⏱️',
      '⏲️',
      '⏰',
      '🕰️',
      '⌛',
      '⏳',
      '📡',
      '🔋',
      '🔌',
      '💡',
      '🔦',
      '🕯️',
      '🪔',
      '🧯',
      '🛢️',
      '💸',
      '💵',
      '💴',
      '💶',
      '💷',
      '💰',
      '💳',
      '💎',
      '⚖️',
      '🦯',
      '🧰',
      '🔧',
      '🔨',
      '⚒️',
      '🛠️',
      '⛏️',
      '🔩',
      '⚙️',
      '🧱',
      '⛓️',
      '🧲',
      '🔫',
      '💣',
      '🧨',
      '🪓',
      '🔪',
      '🗡️',
      '⚔️',
      '🛡️',
      '🚬',
      '⚰️',
      '⚱️',
      '🏺',
      '🔮',
      '📿',
      '🧿',
      '💈',
      '⚗️',
      '🔭',
      '🔬',
      '🕳️',
      '🩹',
      '🩺',
      '💊',
      '💉',
      '🩸',
      '🧬',
      '🦠',
      '🧫',
      '🧪',
      '🌡️',
      '🧹',
      '🧺',
      '🧻',
      '🚽',
      '🚰',
      '🚿',
      '🛁',
      '🛀',
      '🧼',
      '🪒',
      '🧽',
      '🧴',
      '🛎️',
      '🔑',
      '🗝️',
      '🚪',
      '🪑',
      '🛋️',
      '🛏️',
      '🛌',
      '🧸',
      '🖼️',
      '🛍️',
      '🛒',
      '🎁',
      '🎈',
      '🎏',
      '🎀',
      '🎊',
      '🎉',
      '🎎',
      '🏮',
      '🎐',
      '✉️',
      '📩',
      '📨',
      '📧',
      '💌',
      '📥',
      '📤',
      '📦',
      '🏷️',
      '📪',
      '📫',
      '📬',
      '📭',
      '📮',
      '📯',
      '📜',
      '📃',
      '📄',
      '📑',
      '🧾',
      '📊',
      '📈',
      '📉',
      '🗒️',
      '🗓️',
      '📆',
      '📅',
      '🗑️',
      '📇',
      '🗃️',
      '🗳️',
      '🗄️',
      '📋',
      '📁',
      '📂',
      '🗂️',
      '🗞️',
      '📰',
      '📓',
      '📔',
      '📒',
      '📕',
      '📗',
      '📘',
      '📙',
      '📚',
      '📖',
      '🔖',
      '🧷',
      '🔗',
      '📎',
      '🖇️',
      '📐',
      '📏',
      '🧮',
      '📌',
      '📍',
      '✂️',
      '🖊️',
      '🖋️',
      '✒️',
      '🖌️',
      '🖍️',
      '📝',
      '✏️',
      '🔍',
      '🔎',
      '🔏',
      '🔐',
      '🔒',
      '🔓'
    ];

    _emojiCategories['Travel & Transport'] = [
      '🚂',
      '🚃',
      '🚄',
      '🚅',
      '🚆',
      '🚇',
      '🚈',
      '🚉',
      '🚊',
      '🚝',
      '🚞',
      '🚋',
      '🚌',
      '🚍',
      '🚎',
      '🚐',
      '🚑',
      '🚒',
      '🚓',
      '🚔',
      '🚕',
      '🚖',
      '🚗',
      '🚘',
      '🚙',
      '🚚',
      '🚛',
      '🚜',
      '🏎️',
      '🏍️',
      '🛵',
      '🚲',
      '🛴',
      '🛹',
      '🚏',
      '🛣️',
      '🛤️',
      '⛽',
      '🚨',
      '🚥',
      '🚦',
      '🛑',
      '🚧',
      '⚓',
      '⛵',
      '🛶',
      '🚤',
      '🛳️',
      '⛴️',
      '🛥️',
      '🚢',
      '✈️',
      '🛩️',
      '🛫',
      '🛬',
      '🪂',
      '💺',
      '🚁',
      '🚟',
      '🚠',
      '🚡',
      '🛰️',
      '🚀',
      '🛸'
    ];

    _emojiCategories['Symbols & Signs'] = [
      '❤️',
      '🧡',
      '💛',
      '💚',
      '💙',
      '💜',
      '🖤',
      '🤍',
      '🤎',
      '💔',
      '❣️',
      '💕',
      '💞',
      '💓',
      '💗',
      '💖',
      '💘',
      '💝',
      '💟',
      '☮️',
      '✝️',
      '☪️',
      '🕉️',
      '☸️',
      '✡️',
      '🔯',
      '🕎',
      '☯️',
      '☦️',
      '🛐',
      '⛎',
      '♈',
      '♉',
      '♊',
      '♋',
      '♌',
      '♍',
      '♎',
      '♏',
      '♐',
      '♑',
      '♒',
      '♓',
      '🆔',
      '⚛️',
      '🉑',
      '☢️',
      '☣️',
      '📴',
      '📳',
      '🈶',
      '🈚',
      '🈸',
      '🈺',
      '🈷️',
      '✴️',
      '🆚',
      '💮',
      '🉐',
      '㊙️',
      '㊗️',
      '🈴',
      '🈵',
      '🈹',
      '🈲',
      '🅰️',
      '🅱️',
      '🆎',
      '🆑',
      '🅾️',
      '🆘',
      '❌',
      '⭕',
      '🛑',
      '⛔',
      '📛',
      '🚫',
      '💯',
      '💢',
      '♨️',
      '🚷',
      '🚯',
      '🚳',
      '🚱',
      '🔞',
      '📵',
      '🚭',
      '❗',
      '❕',
      '❓',
      '❔',
      '‼️',
      '⁉️',
      '🔅',
      '🔆',
      '〽️',
      '⚠️',
      '🚸',
      '🔱',
      '⚜️',
      '🔰',
      '♻️',
      '✅',
      '🈯',
      '💹',
      '❇️',
      '✳️',
      '❎',
      '🌐',
      '💠',
      'Ⓜ️',
      '🌀',
      '💤',
      '🏧',
      '🚾',
      '♿',
      '🅿️',
      '🈳',
      '🈂️',
      '🛂',
      '🛃',
      '🛄',
      '🛅',
      '🚹',
      '🚺',
      '🚼',
      '🚻',
      '🚮',
      '🎦',
      '📶',
      '🈁',
      '🔣',
      'ℹ️',
      '🔤',
      '🔡',
      '🔠',
      '🆖',
      '🆗',
      '🆙',
      '🆒',
      '🆕',
      '🆓',
      '0️⃣',
      '1️⃣',
      '2️⃣',
      '3️⃣',
      '4️⃣',
      '5️⃣',
      '6️⃣',
      '7️⃣',
      '8️⃣',
      '9️⃣',
      '🔟',
      '🔢',
      '#️⃣',
      '*️⃣',
      '⏏️',
      '▶️',
      '⏸️',
      '⏯️',
      '⏹️',
      '⏺️',
      '⏭️',
      '⏮️',
      '⏩',
      '⏪',
      '⏫',
      '⏬',
      '◀️',
      '🔼',
      '🔽',
      '➡️',
      '⬅️',
      '⬆️',
      '⬇️',
      '↗️',
      '↘️',
      '↙️',
      '↖️',
      '↕️',
      '↔️',
      '↪️',
      '↩️',
      '⤴️',
      '⤵️',
      '🔀',
      '🔁',
      '🔂',
      '🔄',
      '🔃',
      '🎵',
      '🎶',
      '➕',
      '➖',
      '➗',
      '♾️',
      '💲',
      '💱',
      '™️',
      '©️',
      '®️',
      '〰️',
      '➰',
      '➿',
      '🔚',
      '🔙',
      '🔛',
      '🔝',
      '🔜',
      '✔️',
      '☑️',
      '🔘',
      '🔴',
      '🟠',
      '🟡',
      '🟢',
      '🔵',
      '🟣',
      '⚫',
      '⚪',
      '🟤',
      '🔺',
      '🔻',
      '🔸',
      '🔹',
      '🔶',
      '🔷',
      '🔳',
      '🔲',
      '▪️',
      '▫️',
      '◾',
      '◽',
      '◼️',
      '◻️',
      '🟥',
      '🟧',
      '🟨',
      '🟩',
      '🟦',
      '🟪',
      '⬛',
      '⬜',
      '🟫',
      '🔈',
      '🔇',
      '🔉',
      '🔊',
      '🔔',
      '🔕',
      '📣',
      '📢',
      '👁️‍🗨️',
      '💬',
      '💭',
      '🗯️'
    ];

    // Initialize category tabs
    _categoryTabs = ['All', ..._emojiCategories.keys.toList()];

    // Initialize search keywords
    _initializeKeywords();
  }

  void _initializeKeywords() {
    // Add search keywords for better search experience
    _emojiKeywords.addAll({
      '😀': 'grinning face happy smile',
      '😂': 'tears of joy laughing funny',
      '❤️': 'heart love red',
      '🚀': 'rocket space launch',
      '🎉': 'party celebration tada',
      '⭐': 'star',
      '🔥': 'fire hot lit',
      '👍': 'thumbs up like good',
      '🎂': 'birthday cake',
      '🎄': 'christmas tree',
      '🎁': 'gift present',
      '📱': 'phone mobile smartphone',
      '💻': 'laptop computer',
      '☕': 'coffee tea drink',
      '🍕': 'pizza food italian',
      '🍎': 'apple fruit red',
      '🐱': 'cat pet animal',
      '🐶': 'dog pet animal',
      '🌞': 'sun sunny weather',
      '🌙': 'moon night',
      '🌈': 'rainbow colorful',
      '🎵': 'music note sound',
      '⚽': 'soccer football sport',
      '🎮': 'video game controller',
      '💡': 'light bulb idea',
      '🔑': 'key lock security',
      '💰': 'money cash rich',
      '🎓': 'graduation cap student',
      '🏆': 'trophy winner prize',
      '🚗': 'car vehicle auto',
      '✈️': 'airplane travel flight',
      '🏠': 'house home building',
      '🌺': 'flower blossom nature',
      '📚': 'books study library',
      '⏰': 'alarm clock time',
      '🔍': 'magnifying glass search',
      '🎨': 'art paint palette',
      '🏀': 'basketball sport game',
      '🎸': 'guitar music instrument',
      '🍺': 'beer drink alcohol',
      '🌮': 'taco food mexican',
      '👑': 'crown king queen royal',
      '⚡': 'lightning bolt fast electric',
      '🎯': 'dart target bullseye',
      '🔒': 'lock security private',
      '💎': 'diamond gem jewel',
      '🏝️': 'island beach tropical',
      '🎊': 'confetti party celebration',
      '👋': 'wave hello goodbye',
      '🙏': 'pray thank you please',
      '😍': 'heart eyes love adore',
      '🥰': 'smiling hearts love',
      '🤔': 'thinking thought question',
      '😴': 'sleep tired sleepy',
      '🥳': 'partying face celebrate',
      '😎': 'cool sunglasses awesome',
      '🤯': 'exploding head mind blown',
      '🥺': 'pleading face puppy eyes',
      '😭': 'crying sad sobbing',
      '😡': 'angry mad furious',
      '🤢': 'nauseated sick disgusted',
      '🤮': 'vomiting sick puke',
      '🤧': 'sneezing sick allergy',
      '😷': 'mask doctor sick',
      '🤠': 'cowboy hat western',
      '👻': 'ghost scary boo',
      '💀': 'skull death dead',
      '👑': 'crown king queen',
      '🎅': 'santa christmas',
      '🤶': 'mrs claus christmas',
      '🦸': 'superhero hero',
      '🧙': 'wizard magic',
      '🧚': 'fairy magical',
      '🎹': 'piano keyboard music',
      '🥁': 'drum music instrument',
      '🎤': 'microphone sing music',
      '🎧': 'headphones music listen',
      '🎬': 'clapperboard movie film',
      '🏈': 'football american sport',
      '⚾': 'baseball sport game',
      '🎾': 'tennis sport racket',
      '🏐': 'volleyball sport',
      '🎱': 'pool billiards 8ball',
      '🥊': 'boxing glove fight',
      '🛹': 'skateboard skate',
      '🛴': 'scooter kick',
      '🚲': 'bicycle bike cycling',
      '🏍️': 'motorcycle bike',
      '🛸': 'ufo alien spaceship',
      '💺': 'seat chair',
      '🚁': 'helicopter fly',
      '🛶': 'canoe boat paddle',
      '⛵': 'sailboat sailing',
      '🚤': 'speedboat fast boat',
      '🛳️': 'passenger ship cruise',
      '🚢': 'ship boat sea',
      '🏰': 'castle europe palace',
      '🗼': 'tokyo tower eiffel',
      '🗽': 'statue liberty new york',
      '⛪': 'church religion',
      '🕌': 'mosque islam',
      '🕍': 'synagogue jewish',
      '⛩️': 'shinto shrine japan',
      '🎡': 'ferris wheel amusement',
      '🎢': 'roller coaster thrill',
      '🎠': 'carousel horse merry',
      '🏟️': 'stadium sports arena',
      '🎭': 'theater drama mask',
      '🧵': 'thread sewing needle',
      '🧶': 'yarn knitting wool',
      '🎪': 'circus tent big top',
      '🎲': 'dice game random',
      '🧩': 'puzzle piece jigsaw',
      '🪀': 'yo-yo toy play',
      '🪁': 'kite fly wind',
      '🔫': 'water gun pistol toy',
      '🕹️': 'joystick arcade game',
      '🎰': 'slot machine gambling',
      '🎳': 'bowling ball pins',
    });
  }

  List<String> _getAllEmojis() {
    return _emojiCategories.values.expand((list) => list).toList();
  }

  List<String> _getEmojisForCategory(String category) {
    if (category == 'All') {
      return _getAllEmojis();
    }
    return _emojiCategories[category] ?? [];
  }

  void _filterEmojis() {
    final query = _searchController.text.toLowerCase().trim();

    if (query.isEmpty) {
      setState(() {
        _filteredEmojis = _getEmojisForCategory(_selectedCategory);
      });
    } else {
      final categoryEmojis = _getEmojisForCategory(_selectedCategory);
      setState(() {
        _filteredEmojis = categoryEmojis.where((emoji) {
          // Search in emoji character
          if (emoji.toLowerCase().contains(query)) return true;

          // Search in keywords
          final keywords = _emojiKeywords[emoji] ?? '';
          return keywords.toLowerCase().contains(query);
        }).toList();
      });
    }
  }

  void _selectCategory(String category) {
    setState(() {
      _selectedCategory = category;
      _filteredEmojis = _getEmojisForCategory(category);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Select Emoji'),
        backgroundColor: Colors.transparent,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () => Navigator.pop(context),
        ),
      ),
      body: Column(
        children: [
          // Search Bar
          Padding(
            padding: const EdgeInsets.all(16.0),
            child: TextField(
              controller: _searchController,
              decoration: InputDecoration(
                hintText: 'Search emojis...',
                prefixIcon: const Icon(Icons.search),
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
                filled: true,
                fillColor: Theme.of(context).cardColor,
              ),
            ),
          ),

          // Category Tabs
          SizedBox(
            height: 50,
            child: _isLoading
                ? const Center(child: CircularProgressIndicator())
                : ListView.builder(
                    scrollDirection: Axis.horizontal,
                    itemCount: _categoryTabs.length,
                    itemBuilder: (context, index) {
                      final category = _categoryTabs[index];
                      final isSelected = _selectedCategory == category;

                      return Padding(
                        padding: const EdgeInsets.symmetric(horizontal: 4),
                        child: FilterChip(
                          label: Text(category),
                          selected: isSelected,
                          onSelected: (selected) => _selectCategory(category),
                          backgroundColor: Colors.transparent,
                          selectedColor:
                              Theme.of(context).primaryColor.withOpacity(0.2),
                          checkmarkColor: Theme.of(context).primaryColor,
                          labelStyle: TextStyle(
                            color: isSelected
                                ? Theme.of(context).primaryColor
                                : Theme.of(context).textTheme.bodyLarge?.color,
                          ),
                          shape: StadiumBorder(
                            side: BorderSide(
                              color: isSelected
                                  ? Theme.of(context).primaryColor
                                  : Colors.grey[300]!,
                            ),
                          ),
                        ),
                      );
                    },
                  ),
          ),

          const SizedBox(height: 8),

          // Emoji Grid
          Expanded(
            child: _isLoading
                ? const Center(child: CircularProgressIndicator())
                : _filteredEmojis.isEmpty
                    ? const Center(
                        child: Column(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Icon(Icons.emoji_emotions_outlined,
                                size: 64, color: Colors.grey),
                            SizedBox(height: 16),
                            Text(
                              'No emojis found',
                              style:
                                  TextStyle(fontSize: 16, color: Colors.grey),
                            ),
                          ],
                        ),
                      )
                    : GridView.builder(
                        padding: const EdgeInsets.all(16),
                        gridDelegate:
                            const SliverGridDelegateWithFixedCrossAxisCount(
                          crossAxisCount: 8,
                          crossAxisSpacing: 8,
                          mainAxisSpacing: 8,
                        ),
                        itemCount: _filteredEmojis.length,
                        itemBuilder: (context, index) {
                          final emoji = _filteredEmojis[index];
                          final isSelected = widget.currentEmoji == emoji;

                          return GestureDetector(
                            onTap: () {
                              widget.onEmojiSelected(emoji);
                              Navigator.pop(context);
                            },
                            child: Container(
                              decoration: BoxDecoration(
                                color: isSelected
                                    ? Theme.of(context)
                                        .primaryColor
                                        .withOpacity(0.2)
                                    : Colors.transparent,
                                borderRadius: BorderRadius.circular(8),
                                border: isSelected
                                    ? Border.all(
                                        color: Theme.of(context).primaryColor,
                                        width: 2,
                                      )
                                    : null,
                              ),
                              child: Center(
                                child: Text(
                                  emoji,
                                  style: const TextStyle(fontSize: 24),
                                ),
                              ),
                            ),
                          );
                        },
                      ),
          ),
        ],
      ),
    );
  }
}
